name: Run TestNG Tests
on:
  pull_request:
    branches:
      - master
    paths:
      - 'src/test/java/**'
  workflow_dispatch:  # Enables manual triggering
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '11'
      - name: Cache Maven Dependencies
        uses: actions/cache@v3
        with:
          path: ~/.m2
          key: maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            maven-
      - name: Install Maven
        run: sudo apt-get install -y maven
      - name: Run Tests
        run: mvn test -D suite=pom.xml
