name: Run TestNG Tests

on:
  pull_request:
    branches:
      - master
    paths:
      - 'src/test/java/**'
  workflow_dispatch:  # Enables manual triggering

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '11'

      - name: Cache Maven Dependencies
        uses: actions/cache@v3
        with:
          path: ~/.m2
          key: maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            maven-

      - name: Install Maven
        run: sudo apt-get install -y maven

      - name: Start LambdaTest Tunnel
        env:
          LT_USERNAME: ${{ secrets.LT_USERNAME }}
          LT_ACCESS_KEY: ${{ secrets.LT_ACCESS_KEY }}
        run: |
          wget https://downloads.lambdatest.com/tunnel/v3/linux/lambdatest-tunnel.zip
          unzip lambdatest-tunnel.zip
          ./LT -user $LT_USERNAME -key $LT_ACCESS_KEY -tunnelName github-tunnel &
          sleep 15  # Ensure tunnel is established before running tests

      - name: Run Tests on LambdaTest
        env:
          LT_USERNAME: ${{ secrets.LT_USERNAME }}
          LT_ACCESS_KEY: ${{ secrets.LT_ACCESS_KEY }}
          LT_TUNNEL_NAME: "github-tunnel"
        run: mvn test -DsuiteXmlFile=pom.xml
