name: CI/CD with LambdaTest Tunnel

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install Dependencies
        run: npm install

      - name: Start LambdaTest Tunnel
        env:
          LT_USERNAME: ${{ secrets.LT_USERNAME }}
          LT_ACCESS_KEY: ${{ secrets.LT_ACCESS_KEY }}
        run: |
          wget https://downloads.lambdatest.com/tunnel/v3/linux/lambdatest-tunnel.zip
          unzip lambdatest-tunnel.zip
          ./LT -user $LT_USERNAME -key $LT_ACCESS_KEY -tunnelName github-tunnel &
          sleep 15  # Increased wait time to ensure tunnel is established

      - name: Verify LambdaTest Tunnel Connection
        run: curl -Is http://localhost:3000 || echo "Localhost is not accessible"

      - name: Run Selenium Tests on LambdaTest
        env:
          LT_USERNAME: ${{ secrets.LT_USERNAME }}
          LT_ACCESS_KEY: ${{ secrets.LT_ACCESS_KEY }}
          LT_TUNNEL_NAME: "github-tunnel"
        run: node test.js

  deploy:
    needs: test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Deploy Application (Example: AWS S3)
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        run: |
          aws s3 sync ./dist s3://my-bucket-name --delete
