name: Run JUnit Tests with LambdaTest Docker Tunnel

on:
  pull_request:
    branches:
      - master
    paths:
      - 'src/test/java/**'
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '11'

      - name: Cache Maven Dependencies
        uses: actions/cache@v3
        with:
          path: ~/.m2
          key: maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            maven-

      - name: Install Maven
        run: sudo apt-get install -y maven

      - name: Start LambdaTest Tunnel with Docker
        env:
          LT_USERNAME: ${{ secrets.LT_USERNAME }}
          LT_ACCESS_KEY: ${{ secrets.LT_ACCESS_KEY }}
        run: |
          docker run -d --name lambdatest-tunnel \
            -e LT_USERNAME=$LT_USERNAME \
            -e LT_ACCESS_KEY=$LT_ACCESS_KEY \
            -e LT_TUNNEL_NAME=github-tunnel \
            lambdatest/tunnel:latest
          sleep 20  # Allow time for the tunnel to establish

      - name: Verify LambdaTest Tunnel Connection
        run: docker logs lambdatest-tunnel || echo "Tunnel log not found"

      - name: Run JUnit Tests on LambdaTest
        env:
          LT_USERNAME: ${{ secrets.LT_USERNAME }}
          LT_ACCESS_KEY: ${{ secrets.LT_ACCESS_KEY }}
          LT_TUNNEL_NAME: "github-tunnel"
        run: mvn test -Dtest=GFGLoginTest -Dwebdriver.remote.url="https://${LT_USERNAME}:${LT_ACCESS_KEY}@hub.lambdatest.com/wd/hub"

      - name: Stop LambdaTest Tunnel
        run: docker stop lambdatest-tunnel && docker rm lambdatest-tunnel
