name: Run JUnit Tests

on:
  pull_request:
    branches:
      - master
    paths:
      - 'src/test/java/**'
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '11'

      - name: Cache Maven Dependencies
        uses: actions/cache@v3
        with:
          path: ~/.m2
          key: maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            maven-

      - name: Install Maven
        run: sudo apt-get install -y maven

      - name: Start LambdaTest Tunnel
        env:
          LT_USERNAME: ${{ secrets.LT_USERNAME }}
          LT_ACCESS_KEY: ${{ secrets.LT_ACCESS_KEY }}

        run: |
          curl -u "$LT_USERNAME:$LT_ACCESS_KEY" -O https://downloads.lambdatest.com/tunnel/v3/linux/64bit/LT_Linux.zip

          echo $LT_USERNAME
          echo $LT_ACCESS_KEY
          unzip lambdatest-tunnel.zip
          chmod +x LT
          nohup ./LT -user $LT_USERNAME -key $LT_ACCESS_KEY -tunnelName github-tunnel > lt.log 2>&1 &
          sleep 20  # Ensure tunnel is established before running tests

      - name: Check Tunnel Logs
        run: cat lt.log || echo "Tunnel log not found"

      - name: Verify LambdaTest Tunnel Connection
        run: curl -Is http://localhost:3000 || echo "Localhost is not accessible"

      - name: Run JUnit Tests on LambdaTest
        env:
          LT_USERNAME: ${{ secrets.LT_USERNAME }}
          LT_ACCESS_KEY: ${{ secrets.LT_ACCESS_KEY }}
          LT_TUNNEL_NAME: "github-tunnel"
        run: mvn test -Dtest=GFGLoginTest -Dwebdriver.remote.url="https://${LT_USERNAME}:${LT_ACCESS_KEY}@hub.lambdatest.com/wd/hub"
